### ISSUE TITLE
CLI Hacktoberfest Python

### ISSUE THREAD

**Issue by EzazAA** [EzazAA/terminal-cricket#1]
Make the cli more interactive and colourful. its boring !

**Comment by tasbi03** [comment]
can you assign this to me ? and also provide more description for how you want me to work on this ?

**Comment by EzazAA** [comment]
* add a boundary and clean the terminal when entering the game
* Add loading animation
* add a game over screen like this -
 ```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣤⠀⠀⠀⢀⣴⣿⡶⠀⣾⣿⣿⡿⠟⠛⠁
⠀⠀⠀⠀⠀⠀⣀⣀⣄⣀⠀⠀⠀⠀⣶⣶⣦⠀⠀⠀⠀⣼⣿⣿⡇⠀⣠⣿⣿⣿⠇⣸⣿⣿⣧⣤⠀⠀⠀
⠀⠀⢀⣴⣾⣿⡿⠿⠿⠿⠇⠀⠀⣸⣿⣿⣿⡆⠀⠀⢰⣿⣿⣿⣷⣼⣿⣿⣿⡿⢀⣿⣿⡿⠟⠛⠁⠀⠀
⠀⣴⣿⡿⠋⠁⠀⠀⠀⠀⠀⠀⢠⣿⣿⣹⣿⣿⣿⣿⣿⣿⡏⢻⣿⣿⢿⣿⣿⠃⣼⣿⣯⣤⣴⣶⣿⡤⠀
⣼⣿⠏⠀⣀⣠⣤⣶⣾⣷⠄⣰⣿⣿⡿⠿⠻⣿⣯⣸⣿⡿⠀⠀⠀⠁⣾⣿⡏⢠⣿⣿⠿⠛⠋⠉⠀⠀⠀
⣿⣿⠲⢿⣿⣿⣿⣿⡿⠋⢰⣿⣿⠋⠀⠀⠀⢻⣿⣿⣿⠇⠀⠀⠀⠀⠙⠛⠀⠀⠉⠁⠀⠀⠀⠀⠀⠀⠀
⠹⢿⣷⣶⣿⣿⠿⠋⠀⠀⠈⠙⠃⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣤⣴⣶⣦⣤⡀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡇⢰⣶⣶⣾⡿⠷⣿⣿⣿⡟⠛⣉⣿⣿⣿⠆
⠀⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⡎⣿⣿⣦⠀⠀⠀⢀⣤⣾⠟⢀⣿⣿⡟⣁⠀⠀⣸⣿⣿⣤⣾⣿⡿⠛⠁⠀
⠀⠀⠀⠀⣠⣾⣿⡿⠛⠉⢿⣦⠘⣿⣿⡆⠀⢠⣾⣿⠋⠀⣼⣿⣿⣿⠿⠷⢠⣿⣿⣿⠿⢻⣿⣧⠀⠀⠀
⠀⠀⠀⣴⣿⣿⠋⠀⠀⠀⢸⣿⣇⢹⣿⣷⣰⣿⣿⠃⠀⢠⣿⣿⢃⣀⣤⣤⣾⣿⡟⠀⠀⠀⢻⣿⣆⠀⠀
⠀⠀⠀⣿⣿⡇⠀⠀⢀⣴⣿⣿⡟⠀⣿⣿⣿⣿⠃⠀⠀⣾⣿⣿⡿⠿⠛⢛⣿⡟⠀⠀⠀⠀⠀⠻⠿⠀⠀
⠀⠀⠀⠹⣿⣿⣶⣾⣿⣿⣿⠟⠁⠀⠸⢿⣿⠇⠀⠀⠀⠛⠛⠁⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠈⠙⠛⠛⠛⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```
Add colour to all this using `colorama`

**Comment by tasbi03** [comment]
Hey I'm working on the codebase for the game, and I noticed that the current version of the game doesn't have a way for players to quit the game, especially during user input stages (like choosing a number between 1 and 6 or during the toss).

Would it be okay if I add a quit functionality? This would allow users to exit the game by typing 'q' when they don't want to continue. I believe it would improve the user experience by providing a way to gracefully exit the game.

I noticed that the project has two main.py files – one in the root directory and one in the game_files/ directory. I wanted to ask which of these should be the primary entry point for the game, and whether I should focus my changes on the main.py in game_files/ or make changes to both?
Also, just to confirm, I’ve been working on implementing some features (like ASCII art for batting/bowling, game over, etc.) in the game_files/main.py and creating separated files for loading animation under game files. Please let me know if this is the correct file, or if I should adjust anything.
Thanks!

**Comment by EzazAA** [comment]
Sure , it would be great if you implement the ASCII art in a different file and then import it to main.py

**Comment by tasbi03** [comment]
Hey, thanks for getting back to me!

I've implemented the ASCII art as you suggested and put it in separate files, then imported them into main.py. However, I ran into a bit of confusion because I noticed there are two main.py files: one under the game_files/ directory, which I was primarily working on, and another one in build/lib/game_files/, which remains unchanged.

To clarify, I made changes only to the main.py under the game_files/ directory, and to make the game run, I imported the features like this:
```python
from boundary import clear_terminal, print_boundary
from loading import loading_animation
from animation import game_over_screen, goodbye_screen, show_bat, show_ball
```
Could you confirm which of the main.py files should be the primary one that I should be working on? Should I make changes to both? Just want to ensure that I follow the structure you envision for the project.

**Comment by EzazAA** [comment]
You just do it in the root file. The other is for pypi

**Comment by tasbi03** [comment]
Hey I have made pull request , do let me know if something needs changing?

**Comment by tasbi03** [comment]
Hey , I see it says on hacktoberfest website that this repo is not participating in hacktoberfest . can you add tag for "hacktoberfest accepted" so that it can be counted.
